### ISSUE TITLE
Annotations not appearing when annotate is set to true and token is present

### ISSUE THREAD

**Issue by jmealo** [goto-bus-stop/standard-action#10]
Hello,

Thanks for this awesome action! Unfortunately, I'm unable to get annotations to work when following the documentation :(

With the following config:
```yaml
  lint:
    name: StandardJs
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  
    steps:
      - uses: actions/checkout@v2
      - name: Lint with StandardJS
        uses: goto-bus-stop/standard-action@v1
        with:
          annotate: true
        if: always()  # added this out of desperation
```
I have debugged with tmate and verified that the `GITHUB_TOKEN` is present and set with a token that has enough permissions to make annotations.

Here is the action output:
```
Lint with StandardJS
    GITHUB_TOKEN: ***
Run goto-bus-stop/standard-action@v1
  with:
    annotate: true
    version: stylish
    linter: standard
  env:
    GITHUB_TOKEN: ***

/home/runner/work/xx/xx/backend/common/env.js
   15:7    error  'unusedVar' is assigned a value but never used       no-unused-vars
   15:24   error  Extra semicolon                                      semi
   34:9    error  'config' is assigned a value but never used          no-unused-vars
   41:77   error  Extra semicolon                                      semi
   42:71   error  Extra semicolon                                      semi
   80:3    error  Move function declaration to program root            no-inner-declarations
  114:50   error  'processEnvSets' is assigned a value but never used  no-unused-vars
  126:149  error  Expected '===' and instead saw '=='                  eqeqeq
  129:149  error  Expected '===' and instead saw '=='                  eqeqeq

/home/runner/work/xx/xx/backend/common/logger.js
  7:7  error  'path' is assigned a value but never used  no-unused-vars

/home/runner/work/xx/xx/backend/scenarios/index.js
  8:5  error  Parsing error: Unexpected character '#'

/home/runner/work/xx/xx/backend/test.js
   4:1  error  'test' is not defined      no-undef
   8:5  error  'it' is not defined        no-undef
```

I have tried making a pull request with warnings/errors in unchanged files as well as files changed in the pull-request.

I do not get any annotations related to linting, except at the workflow level:
```
Check failure on line 1 in .github
@github-actions github-actions / StandardJs
.github#L1
24 error(s), 0 warning(s) found
```

Any idea what this could be?
